# Generated by Django 3.0.5 on 2020-08-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Task1'), (2, 'Task2'), (3, 'Task3'), (4, 'Task4')])),
                ('task_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('update_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=15)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
